version: '2'
services:
  clima-db:
    image: 'influxdb:1.7.10-alpine'
    container_name: 'clima-db'
    environment:
      - INFLUXDB_DB=climalink
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=secretadmin
      - INFLUXDB_USER=climalink
      - INFLUXDB_USER_PASSWORD=secretuser
    volumes:
      - ./data/clima-influx.db:/var/lib/clima-influx.db
    ports:
      - '8086:8086'
    networks: 
      - clim-network
networks:
    clim-network: